services:
  - type: web
    name: open-recommender-ui
    env: static
    buildCommand: cd packages/client && yarn && yarn build
    staticPublishPath: ./packages/client/dist
    branch: main
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
  - type: web
    plan: free
    name: open-recommender-api
    env: node
    buildCommand: cd packages/server && yarn && yarn build
    startCommand: cd packages/server && yarn start
    branch: main
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: open-recommender
          property: connectionString
