services:
  - type: web
    name: open-recommender-ui
    env: static
    buildCommand: cd packages/shared && yarn && cd ../client && yarn && yarn build
    staticPublishPath: ./packages/client/dist
    branch: main
    buildFilter:
      paths:
        - packages/client/**/*.ts
        - packages/client/**/*.tsx
        - packages/shared/**/*.ts
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
  - type: web
    plan: free
    name: open-recommender-api
    env: python
    buildCommand: yarn && cd packages/server && yarn build
    startCommand: cd packages/server && yarn start
    branch: main
    buildFilter:
      paths:
        - packages/server/**/*.ts
        - packages/shared/**/*.ts
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: open-recommender-db
          property: connectionString
databases:
  - name: open-recommender-db
    plan: free
