services:
  - type: web
    name: open-recommender-ui
    env: static
    buildCommand: cd packages/shared && yarn && cd ../client && yarn && yarn build
    staticPublishPath: ./packages/client/dist
    branch: main
    buildFilter:
      - packages/client/**/*
      - packages/shared/**/*
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
  - type: web
    plan: free
    name: open-recommender-api
    env: node
    buildCommand: cd packages/shared && yarn && cd ../server && yarn
    startCommand: cd packages/server && yarn start
    branch: main
    buildFilter:
      - packages/server/**/*
      - packages/shared/**/*
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: open-recommender-db
          property: connectionString
databases:
  - name: open-recommender-db
    plan: free
